apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-chaos-website
  namespace: default
spec:
  rules:
  - host: www.chaos-website.com
    http:
      paths:
      - backend:
          serviceName: chaos-website
          servicePort: 80
        path: /


